In [1]:
from BO import *
from COBYLA import *
from COBYQA import *
from utils import *
from test_function_constr import *
from ENTMOOT import *

In [2]:
algorithms_test = [
    CBO_opt,
    CBO_TR_opt,
    COBYLA,
    COBYQA,
    opt_ENTMOOT,
    # # CUATRO,
]

functions_test  = [
    'WO_f',
    ]

N_x_l        = [
    2,
    ]               # Number of input dimensions

start_       = [5, 10, 15] # we start counting the last 15 points / 40 points / 85 points from each trajectory instead of all of them

reps         = 1

f_eval_l     = [
    20,
    ]  # These are the number of function evaluations (length of trajectory) foreach run in reps. The number depends on the input dimension N_x_l

bounds  = np.array([[4., 7.], [70., 100.]])
home_dir  = 'images/WO/trajectory_plots_1D_&_tables'
track_x = True
N_x_ = 2
f_eval_=20
i_rep = 0
TR_plot = False

In [3]:
for alg_ in algorithms_test:
    for func_ in functions_test:
        t_ = Test_function(func_, n_x=2, track_x=track_x)
        a, b, team_names, cids, X_opt_plot, TR_l, xnew, backtrck_l, samples_number = alg_(t_, N_x_, bounds, f_eval_, i_rep)
        ML4CE_con_contours(t_, alg_, bounds, X_opt_plot, xnew, samples_number, func_, TR_plot, TR_l, SafeFig = False)

- preliminar data supplied, computing objective and constraint values
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[<bound method Test_function.fun_test of <test_function_constr.Test_function object at 0x00000221C86E44D0>>, <bound method Test_function.WO_con1_test of <test_function_constr.Test_function object at 0x00000221C86E44D0>>, <bound method Test_function.WO_con2_test of <test_function_constr.Test_function object at 0x00000221C86E44D0>>]
[[74.14698358 68.79598163 80.30582093  7.72270879 76.26130718 -6.25752926
  13.32643991 91.08645555 -7.886886   79.21256876]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]]
[[ 7.41469836e+01  6.87959816e+01  8.03058209e+01  7.72270879e+00
   7.62613072e+01 -6.25752926e+00  1.33264399e+01  9.10864556e+01
  -7.

 90%|█████████ | 9/10 [00:17<00:02,  2.81s/it]